<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="MongoDb.Generic.Repository" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Swgoh.Application\Swgoh.Application.csproj" />
    <ProjectReference Include="..\Swgoh.Domain\Swgoh.Domain.csproj" />
  </ItemGroup>
</Project>
